### ISSUE TITLE
Hoeveel gebruik je van deze framework?

### ISSUE THREAD

**Issue by BerendWeij** [kendaru/Solution-Finder#1]
```c
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css"> 
```

Bestand: https://github.com/kendaru/Solution-Finder/blob/master/index.html

Probeer alleen frameworks te gebruiken als je er echt veel van nodig hebt. In het geval van deze opdracht kan ik me niet voorstellen dat je perse een responsive framework nodig hebt.

Met css styles als display block, inline-block, table, row en table-cell kom je al een heel aardig eind.
Helemaal als je het koppelt met Sassy CSS en bijvoorbeeld mixins.

**Comment by kendaru** [comment]
removed - https://github.com/kendaru/Solution-Finder/commit/1c186ff6fc974a0e76c8526b28cb8089ffcc9836
