### ISSUE TITLE
Gebruik hele namen voor je variabelen

### ISSUE THREAD

**Issue by BerendWeij** [kendaru/Solution-Finder#2]
```c
var elms = { 
```

Bestand: https://github.com/kendaru/Solution-Finder/blob/master/main.js

Gebruik hele namen voor je variabelen. Met minification kunnen we het straks nog optimaliseren qua lengte. Dan maken we ze wel weer klein. Tot die tijd geldt: leesbaarheid boven alles.

Een uitzondering hiervoor zijn de indexes van een loop (bijvoorbeeld var i )

**Comment by ikzelf01** [comment]
Changed,
https://github.com/kendaru/Solution-Finder/commit/f3252808c92a72ed1b19422036adca59d0d61de6
https://github.com/kendaru/Solution-Finder/commit/4d2e99f440261bff4cccff8a0a73d8fb78e0e4fd
