### ISSUE TITLE
View logic los van application logic

### ISSUE THREAD

**Issue by BerendWeij** [kendaru/Solution-Finder#3]
```c
function onAnswerClick(e){
        e.preventDefault();


        if (this.dataset.goto.contains(':')) {
            var data = this.dataset.goto.split(':');
            switch (data[0]) {
                case 'info':
                    console.log(data[1]);
                    break;

                case 'form':
                    console.log(data[1]);
                    break;

                case 'overzicht':
                    console.log(data[1]);
                    break;
            }

        } else if (this.dataset.goto > 0){
            setQuestion(this.dataset.goto);
        }

        progress.push({
            "value": this.innerHTML,
            "question": this.dataset.question
        });
        updateProgress();
    } 
```

Bestand: https://github.com/kendaru/Solution-Finder/blob/master/main.js

Houdt je view/interface/input code los van je applicatie logica. Nu is er een harde afhankelijkheid en is de logica niet te hergebruiken. Er is een harde koppeling naar waar je naar luistert (event) en hetgeen dat je wilt dat er kan gebeuren.

Een goede les is het om eerst de applicatie logica te schrijven. Wat wil je dat er mogelijk is. Schrijf hiervoor alle functies. Bijvoorbeeld:
- next()
- previous()
- load()
Deze functies krijgen niet een event als parameter.

Vervolgens schrijf je view logica / controller logica om deze functies aan te roepen. Bijvoorbeeld een muisklik listener die één van bovenstaande functies aanroept. Dit maakt je code een stuk vrijer.

**Comment by kendaru** [comment]
veranderd vanaf https://github.com/kendaru/Solution-Finder/commit/467c6ad2317c91f2f7830fb0e4ac017cf072b782
